# Generated by Django 6.0.6 on 2026-06-11 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Wildfire', 'Wildfire'), ('Storm', 'Storm'), ('Drought', 'Drought'), ('Cyclone', 'Cyclone'), ('Landslide', 'Landslide'), ('Other', 'Other')], default='Flood', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('affected_count', models.IntegerField(default=0)),
                ('coord_x', models.FloatField(default=50)),
                ('coord_y', models.FloatField(default=50)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('need_medical', models.IntegerField(default=0)),
                ('need_food', models.IntegerField(default=0)),
                ('need_shelter', models.IntegerField(default=0)),
                ('need_rescue', models.IntegerField(default=0)),
                ('priority_score', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('medical', 'Medical Unit'), ('rescue', 'Rescue Team'), ('food', 'Food/Water Supply'), ('shelter', 'Shelter Kit')], default='medical', max_length=20)),
                ('status', models.CharField(choices=[('standby', 'Standby'), ('deployed', 'Deployed'), ('in-transit', 'In Transit'), ('unavailable', 'Unavailable')], default='standby', max_length=20)),
                ('capacity', models.IntegerField(default=100)),
                ('utilized', models.IntegerField(default=0)),
                ('location', models.CharField(default='Base Camp', max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('assigned_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Wildfire', 'Wildfire'), ('Storm', 'Storm'), ('Drought', 'Drought'), ('Cyclone', 'Cyclone'), ('Landslide', 'Landslide'), ('Other', 'Other')], default='Flood', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('people_affected', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('reporter_name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('reporter_contact', models.CharField(blank=True, max_length=50)),
                ('is_voicebot', models.BooleanField(default=False)),
                ('voicebot_transcript', models.TextField(blank=True)),
                ('ai_priority_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('allocated', 'Allocated'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.resource')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.zone')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
