# Generated by Django 6.0.6 on 2026-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='data_source',
            field=models.CharField(default='NDMA Weather Station Network', max_length=150),
        ),
        migrations.AddField(
            model_name='zone',
            name='district',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='state',
            field=models.CharField(default='Telangana', max_length=100),
        ),
    ]
